language: java
jdk:
  - openjdk8
services:
  - postgresql
  - database: CONSTRUCAOCIVIL_DEVELOP
  - username: test
before_script:
   - psql -c 'create database CONSTRUCAOCIVIL_DEVELOP;' -U postgres
   - psql -c "create user test with password '123';" -U postgres
notifications:
  email:
    recipients:
      - eduardo.gf@outlook.com.br
on_success: always